services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  frauddetectionservice:
    build:
      context: .
      dockerfile: FraudDetectionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      - banking-network

  ledger-service:
    build:
      context: .
      dockerfile: LedgerService/Dockerfile
    container_name: ledger-service
    ports:
      - "5004:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      ledger-postgres:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${LEDGER_DB_CONNECTION}
      - Services__AccountServiceUrl=${ACCOUNT_SERVICE_URL}
    restart: on-failure
    networks:
      - banking-network

  notificationservice:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Email__From=noreply@bankingsystem.com
      - Email__SmtpServer=sandbox.smtp.mailtrap.io
      - Email__Port=587
      - Email__Username=0f09aa8b0aab1d
      - Email__Password=74cd756568e0bc
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      - banking-network

  dashboard:
    build:
      context: ./Dashboard
    ports:
      - "5000:80"
    restart: always
    networks:
      - banking-network

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "5001:80"
    depends_on:
      - user-postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${USER_DB_CONNECTION}
    networks:
      - banking-network

  account-service:
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    container_name: account-service
    ports:
      - "5002:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      account-postgres:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${ACCOUNT_DB_CONNECTION}
    networks:
      - banking-network

  transaction-service:
    build:
      context: .
      dockerfile: TransactionService/Dockerfile
    container_name: transaction-service
    ports:
      - "5003:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      account-service:
        condition: service_started
      ledger-service:
        condition: service_started
      transaction-postgres:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${TRANSACTION_DB_CONNECTION}
      - Services__AccountServiceUrl=${ACCOUNT_SERVICE_URL}
      - Services__LedgerServiceUrl=${LEDGER_SERVICE_URL}
    networks:
      - banking-network

  user-postgres:
    image: postgres
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - banking-network

  account-postgres:
    image: postgres
    container_name: account-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: accountdb
    ports:
      - "5434:5432"
    volumes:
      - account_pgdata:/var/lib/postgresql/data
    networks:
      - banking-network

  ledger-postgres:
    image: postgres
    container_name: ledger-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: ledgerdb
    ports:
      - "5435:5432"
    volumes:
      - ledger_pgdata:/var/lib/postgresql/data
    networks:
      - banking-network

  transaction-postgres:
    image: postgres
    container_name: transaction-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: transactiondb
    ports:
      - "5436:5432"
    volumes:
      - transaction_pgdata:/var/lib/postgresql/data
    networks:
      - banking-network

volumes:
  user_pgdata:
  account_pgdata:
  ledger_pgdata:
  transaction_pgdata:

networks:
  banking-network: