version: '3.9'

services:

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "5001:80"
    depends_on:
      - user-postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${USER_DB_CONNECTION}

  account-service:
    build:
      context: ./AccountService
    container_name: account-service
    ports:
      - "5002:80"
    depends_on:
      - account-postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${ACCOUNT_DB_CONNECTION}

  transaction-service:
    build:
      context: ./TransactionService
    container_name: transaction-service
    ports:
      - "5003:80"
    depends_on:
      - account-service
      - ledger-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${TRANSACTION_DB_CONNECTION}
      - Services__AccountServiceUrl=${ACCOUNT_SERVICE_URL}
      - Services__LedgerServiceUrl=${LEDGER_SERVICE_URL}

  ledger-service:
    build:
      context: ./LedgerService
    container_name: ledger-service
    ports:
      - "5004:80"
    depends_on:
      - ledger-postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ConnectionStrings__DefaultConnection=${LEDGER_DB_CONNECTION}
      - Services__AccountServiceUrl=${ACCOUNT_SERVICE_URL}

  # PostgreSQL for UserService
  user-postgres:
    image: postgres
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  # PostgreSQL for AccountService
  account-postgres:
    image: postgres
    container_name: account-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: accountdb
    ports:
      - "5434:5432"
    volumes:
      - account_pgdata:/var/lib/postgresql/data

  # PostgreSQL for LedgerService
  ledger-postgres:
    image: postgres
    container_name: ledger-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: ledgerdb
    ports:
      - "5435:5432"
    volumes:
      - ledger_pgdata:/var/lib/postgresql/data

  # PostGreSQL for TransactionService
  transaction-postgres:
    image: postgres
    container_name: transaction-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darko
      POSTGRES_DB: transactiondb
    ports:
      - "5436:5432"
    volumes:
      - transaction_pgdata:/var/lib/postgresql/data

volumes:
  user_pgdata:
  account_pgdata:
  ledger_pgdata:
  transaction_pgdata:
